export type UserType = 'locataire' | 'proprietaire' | 'agence' | 'admin';
export type UserRole = 'admin' | 'user' | 'agent' | 'moderator';
export type PropertyCategory = 'residentiel' | 'commercial';
export type PropertyType = 'appartement' | 'maison' | 'villa' | 'studio' | 'duplex' | 'chambre' | 'bureau' | 'commerce' | 'entrepot' | 'terrain';
export type PropertyStatus = 'disponible' | 'loue' | 'en_attente' | 'retire';
export type ApplicationStatus = 'en_attente' | 'acceptee' | 'refusee' | 'annulee';
export type VerificationStatus = 'en_attente' | 'verifie' | 'rejete';
export type PaymentStatus = 'en_attente' | 'complete' | 'echoue' | 'annule';
export type PaymentType = 'loyer' | 'depot_garantie' | 'charges' | 'frais_agence';
export type PaymentMethod = 'mobile_money' | 'carte_bancaire' | 'virement' | 'especes';
export type LeaseStatus = 'draft' | 'pending' | 'active' | 'expired' | 'terminated' | 'cancelled';
export type LeaseType = 'courte_duree' | 'longue_duree';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          user_type: string;
          active_role: string | null;
          available_roles: string[];
          full_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          bio: string | null;
          city: string | null;
          address: string | null;
          is_verified: boolean;
          profile_setup_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          user_type?: string;
          active_role?: string | null;
          available_roles?: string[];
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          city?: string | null;
          address?: string | null;
          is_verified?: boolean;
          profile_setup_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          user_type?: string;
          active_role?: string | null;
          available_roles?: string[];
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          city?: string | null;
          address?: string | null;
          is_verified?: boolean;
          profile_setup_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      properties: {
        Row: {
          id: string;
          owner_id: string;
          title: string;
          description: string | null;
          address: string;
          city: string;
          neighborhood: string | null;
          latitude: number | null;
          longitude: number | null;
          property_type: PropertyType;
          property_category: PropertyCategory;
          status: PropertyStatus;
          bedrooms: number;
          bathrooms: number;
          surface_area: number | null;
          has_parking: boolean;
          has_garden: boolean;
          is_furnished: boolean;
          has_ac: boolean;
          monthly_rent: number;
          deposit_amount: number | null;
          charges_amount: number;
          images: string[];
          main_image: string | null;
          view_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          title: string;
          description?: string | null;
          address: string;
          city: string;
          neighborhood?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          property_type: PropertyType;
          property_category?: PropertyCategory;
          status?: PropertyStatus;
          bedrooms?: number;
          bathrooms?: number;
          surface_area?: number | null;
          has_parking?: boolean;
          has_garden?: boolean;
          is_furnished?: boolean;
          has_ac?: boolean;
          monthly_rent: number;
          deposit_amount?: number | null;
          charges_amount?: number;
          images?: string[];
          main_image?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          title?: string;
          description?: string | null;
          address?: string;
          city?: string;
          neighborhood?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          property_type?: PropertyType;
          property_category?: PropertyCategory;
          status?: PropertyStatus;
          bedrooms?: number;
          bathrooms?: number;
          surface_area?: number | null;
          has_parking?: boolean;
          has_garden?: boolean;
          is_furnished?: boolean;
          has_ac?: boolean;
          monthly_rent?: number;
          deposit_amount?: number | null;
          charges_amount?: number;
          images?: string[];
          main_image?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      rental_applications: {
        Row: {
          id: string;
          property_id: string;
          tenant_id: string;
          status: ApplicationStatus;
          message: string | null;
          identity_verified_required: boolean;
          identity_verified_at_application: boolean;
          documents: Record<string, any>;
          landlord_response: string | null;
          responded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          tenant_id: string;
          status?: ApplicationStatus;
          message?: string | null;
          identity_verified_required?: boolean;
          identity_verified_at_application?: boolean;
          documents?: Record<string, any>;
          landlord_response?: string | null;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          tenant_id?: string;
          status?: ApplicationStatus;
          message?: string | null;
          identity_verified_required?: boolean;
          identity_verified_at_application?: boolean;
          documents?: Record<string, any>;
          landlord_response?: string | null;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      leases: {
        Row: {
          id: string;
          property_id: string;
          tenant_id: string;
          landlord_id: string;
          start_date: string;
          end_date: string;
          monthly_rent: number;
          deposit_amount: number;
          charges_amount: number;
          status: LeaseStatus;
          lease_type: LeaseType;
          terms: string | null;
          custom_clauses: string | null;
          electronically_signed: boolean;
          tenant_signed: boolean;
          landlord_signed: boolean;
          tenant_signed_at: string | null;
          landlord_signed_at: string | null;
          tenant_otp_verified_at: string | null;
          landlord_otp_verified_at: string | null;
          signed_date: string | null;
          oneci_cev_requested: boolean;
          oneci_cev_number: string | null;
          oneci_cev_fee_paid: boolean;
          oneci_cev_fee_amount: number;
          oneci_cev_issued_at: string | null;
          electronic_stamp_number: string | null;
          electronic_stamp_applied_at: string | null;
          signature_provider: string;
          signature_certificate_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          tenant_id: string;
          landlord_id: string;
          start_date: string;
          end_date: string;
          monthly_rent: number;
          deposit_amount?: number;
          charges_amount?: number;
          status?: LeaseStatus;
          lease_type?: LeaseType;
          terms?: string | null;
          custom_clauses?: string | null;
          electronically_signed?: boolean;
          tenant_signed?: boolean;
          landlord_signed?: boolean;
          tenant_signed_at?: string | null;
          landlord_signed_at?: string | null;
          tenant_otp_verified_at?: string | null;
          landlord_otp_verified_at?: string | null;
          signed_date?: string | null;
          oneci_cev_requested?: boolean;
          oneci_cev_number?: string | null;
          oneci_cev_fee_paid?: boolean;
          oneci_cev_fee_amount?: number;
          oneci_cev_issued_at?: string | null;
          electronic_stamp_number?: string | null;
          electronic_stamp_applied_at?: string | null;
          signature_provider?: string;
          signature_certificate_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          tenant_id?: string;
          landlord_id?: string;
          start_date?: string;
          end_date?: string;
          monthly_rent?: number;
          deposit_amount?: number;
          charges_amount?: number;
          status?: LeaseStatus;
          lease_type?: LeaseType;
          terms?: string | null;
          custom_clauses?: string | null;
          electronically_signed?: boolean;
          tenant_signed?: boolean;
          landlord_signed?: boolean;
          tenant_signed_at?: string | null;
          landlord_signed_at?: string | null;
          tenant_otp_verified_at?: string | null;
          landlord_otp_verified_at?: string | null;
          signed_date?: string | null;
          oneci_cev_requested?: boolean;
          oneci_cev_number?: string | null;
          oneci_cev_fee_paid?: boolean;
          oneci_cev_fee_amount?: number;
          oneci_cev_issued_at?: string | null;
          electronic_stamp_number?: string | null;
          electronic_stamp_applied_at?: string | null;
          signature_provider?: string;
          signature_certificate_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          user1_id: string;
          user2_id: string;
          last_message_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user1_id: string;
          user2_id: string;
          last_message_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user1_id?: string;
          user2_id?: string;
          last_message_at?: string | null;
          created_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          sender_id: string;
          receiver_id: string;
          application_id: string | null;
          content: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          sender_id: string;
          receiver_id: string;
          application_id?: string | null;
          content: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          sender_id?: string;
          receiver_id?: string;
          application_id?: string | null;
          content?: string;
          is_read?: boolean;
          created_at?: string;
        };
      };
      maintenance_requests: {
        Row: {
          id: string;
          property_id: string;
          tenant_id: string;
          landlord_id: string;
          title: string;
          description: string;
          status: string;
          priority: string;
          images: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          tenant_id: string;
          landlord_id: string;
          title: string;
          description: string;
          status?: string;
          priority?: string;
          images?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          tenant_id?: string;
          landlord_id?: string;
          title?: string;
          description?: string;
          status?: string;
          priority?: string;
          images?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      user_verifications: {
        Row: {
          id: string;
          user_id: string;
          identity_verified: boolean;
          identity_verified_at: string | null;
          oneci_verified: boolean;
          oneci_verified_at: string | null;
          oneci_cni_number: string | null;
          oneci_reference_number: string | null;
          cnam_verified: boolean;
          cnam_verified_at: string | null;
          cnam_number: string | null;
          face_verified: boolean;
          face_verified_at: string | null;
          face_verification_provider: string | null;
          face_verification_reference: string | null;
          verification_score: number;
          verification_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          identity_verified?: boolean;
          identity_verified_at?: string | null;
          oneci_verified?: boolean;
          oneci_verified_at?: string | null;
          oneci_cni_number?: string | null;
          oneci_reference_number?: string | null;
          cnam_verified?: boolean;
          cnam_verified_at?: string | null;
          cnam_number?: string | null;
          face_verified?: boolean;
          face_verified_at?: string | null;
          face_verification_provider?: string | null;
          face_verification_reference?: string | null;
          verification_score?: number;
          verification_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          identity_verified?: boolean;
          identity_verified_at?: string | null;
          oneci_verified?: boolean;
          oneci_verified_at?: string | null;
          oneci_cni_number?: string | null;
          oneci_reference_number?: string | null;
          cnam_verified?: boolean;
          cnam_verified_at?: string | null;
          cnam_number?: string | null;
          face_verified?: boolean;
          face_verified_at?: string | null;
          face_verification_provider?: string | null;
          face_verification_reference?: string | null;
          verification_score?: number;
          verification_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      score_history: {
        Row: {
          id: string;
          user_id: string;
          score_type: string;
          old_score: number;
          new_score: number;
          change_reason: string | null;
          metadata: Record<string, any>;
          created_at: string;
        };
      };
      score_settings: {
        Row: {
          id: string;
          setting_key: string;
          setting_value: Record<string, any>;
          description: string | null;
          updated_at: string;
        };
      };
      rental_history: {
        Row: {
          id: string;
          tenant_id: string;
          landlord_id: string;
          property_id: string | null;
          lease_id: string | null;
          start_date: string;
          end_date: string | null;
          monthly_rent: number;
          payment_reliability_score: number;
          property_condition_score: number;
          lease_compliance_score: number;
          landlord_notes: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      owner_ratings: {
        Row: {
          id: string;
          owner_id: string;
          overall_rating: number;
          response_time_score: number;
          contract_completion_rate: number;
          tenant_satisfaction_score: number;
          total_properties: number;
          total_rentals: number;
          updated_at: string;
        };
      };
      score_achievements: {
        Row: {
          id: string;
          user_id: string;
          achievement_type: string;
          achievement_name: string;
          achievement_description: string | null;
          icon: string;
          achieved_at: string;
        };
      };
      payments: {
        Row: {
          id: string;
          lease_id: string;
          payer_id: string;
          amount: number;
          payment_type: PaymentType;
          payment_method: PaymentMethod;
          status: PaymentStatus;
          transaction_id: string | null;
          payment_date: string | null;
          due_date: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lease_id: string;
          payer_id: string;
          amount: number;
          payment_type: PaymentType;
          payment_method: PaymentMethod;
          status?: PaymentStatus;
          transaction_id?: string | null;
          payment_date?: string | null;
          due_date: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lease_id?: string;
          payer_id?: string;
          amount?: number;
          payment_type?: PaymentType;
          payment_method?: PaymentMethod;
          status?: PaymentStatus;
          transaction_id?: string | null;
          payment_date?: string | null;
          due_date?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      mobile_money_transactions: {
        Row: {
          id: string;
          payment_id: string;
          provider: string;
          phone_number: string;
          amount: number;
          fees: number;
          status: string;
          transaction_reference: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          payment_id: string;
          provider: string;
          phone_number: string;
          amount: number;
          fees?: number;
          status?: string;
          transaction_reference: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          payment_id?: string;
          provider?: string;
          phone_number?: string;
          amount?: number;
          fees?: number;
          status?: string;
          transaction_reference?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          property_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          property_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          property_id?: string;
          created_at?: string;
        };
      };
      property_visits: {
        Row: {
          id: string;
          property_id: string;
          tenant_id: string;
          landlord_id: string | null;
          scheduled_date: string;
          status: string;
          visit_type: string | null;
          notes: string | null;
          tenant_notes: string | null;
          landlord_notes: string | null;
          cancellation_reason: string | null;
          created_at: string;
          updated_at: string;
          confirmed_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          property_id: string;
          tenant_id: string;
          landlord_id?: string | null;
          scheduled_date: string;
          status?: string;
          visit_type?: string | null;
          notes?: string | null;
          tenant_notes?: string | null;
          landlord_notes?: string | null;
          cancellation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          confirmed_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          property_id?: string;
          tenant_id?: string;
          landlord_id?: string | null;
          scheduled_date?: string;
          status?: string;
          visit_type?: string | null;
          notes?: string | null;
          tenant_notes?: string | null;
          landlord_notes?: string | null;
          cancellation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          confirmed_at?: string | null;
          completed_at?: string | null;
        };
      };
      reviews: {
        Row: {
          id: string;
          lease_id: string;
          reviewer_id: string;
          reviewed_id: string;
          property_id: string | null;
          rating: number;
          comment: string | null;
          review_type: string;
          is_public: boolean;
          is_verified: boolean;
          response: string | null;
          response_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lease_id: string;
          reviewer_id: string;
          reviewed_id: string;
          property_id?: string | null;
          rating: number;
          comment?: string | null;
          review_type: string;
          is_public?: boolean;
          is_verified?: boolean;
          response?: string | null;
          response_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lease_id?: string;
          reviewer_id?: string;
          reviewed_id?: string;
          property_id?: string | null;
          rating?: number;
          comment?: string | null;
          review_type?: string;
          is_public?: boolean;
          is_verified?: boolean;
          response?: string | null;
          response_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          read: boolean;
          link: string | null;
          metadata: Record<string, any>;
          created_at: string;
          read_at: string | null;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type?: string;
          read?: boolean;
          link?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          read_at?: string | null;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: string;
          read?: boolean;
          link?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          read_at?: string | null;
          expires_at?: string | null;
        };
      };
      saved_searches: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          filters: Record<string, any>;
          notify_new_results: boolean;
          last_checked_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          filters?: Record<string, any>;
          notify_new_results?: boolean;
          last_checked_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          filters?: Record<string, any>;
          notify_new_results?: boolean;
          last_checked_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      disputes: {
        Row: {
          id: string;
          lease_id: string;
          complainant_id: string;
          respondent_id: string;
          mediator_id: string | null;
          title: string;
          description: string;
          category: string;
          status: string;
          priority: string;
          resolution: string | null;
          evidence_files: string[];
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
          closed_at: string | null;
        };
        Insert: {
          id?: string;
          lease_id: string;
          complainant_id: string;
          respondent_id: string;
          mediator_id?: string | null;
          title: string;
          description: string;
          category?: string;
          status?: string;
          priority?: string;
          resolution?: string | null;
          evidence_files?: string[];
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          closed_at?: string | null;
        };
        Update: {
          id?: string;
          lease_id?: string;
          complainant_id?: string;
          respondent_id?: string;
          mediator_id?: string | null;
          title?: string;
          description?: string;
          category?: string;
          status?: string;
          priority?: string;
          resolution?: string | null;
          evidence_files?: string[];
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          closed_at?: string | null;
        };
      };
    };
  };
}
