/*
  # Ajouter des propriétés de démonstration

  1. Propriétés sans owner_id (public)
    - 6 propriétés à Abidjan
    - Différents quartiers et types
    - Prix variés
*/

-- Désactiver temporairement la contrainte NOT NULL sur owner_id si nécessaire
ALTER TABLE properties ALTER COLUMN owner_id DROP NOT NULL;

-- Insérer propriétés de démonstration
INSERT INTO properties (
  title,
  description,
  property_type,
  monthly_rent,
  deposit_amount,
  city,
  neighborhood,
  address,
  bedrooms,
  bathrooms,
  surface_area,
  has_parking,
  has_garden,
  is_furnished,
  has_ac,
  images,
  status,
  latitude,
  longitude,
  view_count
) VALUES 
(
  'Villa Moderne 4 Chambres - Cocody',
  'Magnifique villa moderne avec piscine dans le quartier résidentiel de Cocody. Sécurité 24h/7, parking 3 voitures, jardin tropical.',
  'villa',
  450000,
  900000,
  'Abidjan',
  'Cocody',
  'Rue des Jardins, Cocody',
  4,
  3,
  250,
  true,
  true,
  false,
  true,
  ARRAY['/images/hero-villa-cocody.jpg', '/images/hero-residence-moderne.jpg'],
  'disponible',
  5.3364,
  -4.0267,
  156
),
(
  'Appartement 3P - Plateau Centre',
  'Bel appartement de standing au cœur du Plateau. Vue panoramique, immeuble récent avec ascenseur, générateur.',
  'appartement',
  180000,
  360000,
  'Abidjan',
  'Plateau',
  'Avenue Chardy, Plateau',
  3,
  2,
  120,
  true,
  false,
  false,
  true,
  ARRAY['/images/hero-immeuble-moderne.png', '/images/hero-immeubles-parking.jpg'],
  'disponible',
  5.3205,
  -4.0156,
  243
),
(
  'Studio Meublé - Marcory Zone 4',
  'Studio moderne tout équipé dans résidence sécurisée. Cuisine américaine, climatisation, WIFI inclus.',
  'appartement',
  80000,
  160000,
  'Abidjan',
  'Marcory',
  'Zone 4, Marcory',
  1,
  1,
  35,
  true,
  false,
  true,
  true,
  ARRAY['/images/hero-residence-securisee.jpg', '/images/hero-maison-moderne.jpg'],
  'disponible',
  5.2850,
  -3.9960,
  187
),
(
  'Duplex 5P - Angré 8ème Tranche',
  'Superbe duplex dans quartier calme. 2 niveaux, terrasse, parking couvert. Construction récente.',
  'villa',
  350000,
  700000,
  'Abidjan',
  'Angré',
  '8ème Tranche, Angré',
  5,
  3,
  200,
  true,
  true,
  false,
  true,
  ARRAY['/images/hero-quartiers-abidjan.jpg', '/images/hero-residence-moderne.jpg'],
  'disponible',
  5.3950,
  -3.9845,
  98
),
(
  'Appartement 2P - Yopougon Selmer',
  'Appartement familial dans immeuble bien entretenu. Proche marché, écoles et gare. Loyer accessible.',
  'appartement',
  75000,
  150000,
  'Abidjan',
  'Yopougon',
  'Selmer, Yopougon',
  2,
  1,
  65,
  true,
  false,
  false,
  false,
  ARRAY['/images/hero-logements-sociaux.jpg', '/images/hero-quartier-construction.jpg'],
  'disponible',
  5.3167,
  -4.0833,
  134
),
(
  'Villa 6P avec Piscine - Riviera Golf',
  'Villa de prestige dans le quartier huppé de Riviera Golf. Piscine chauffée, salle de sport, bureau.',
  'villa',
  650000,
  1300000,
  'Abidjan',
  'Riviera',
  'Riviera Golf',
  6,
  4,
  350,
  true,
  true,
  false,
  true,
  ARRAY['/images/hero-abidjan-1.jpg', '/images/hero-abidjan-2.jpg'],
  'disponible',
  5.3700,
  -3.9500,
  201
);
