-- migration: create backup system
-- description: create backup_logs table and backup system
-- created: 2025-12-06T12:00:00Z

-- create backup_logs table
do $$
begin
    create table backup_logs (
        id bigint generated by default as identity primary key,
        backup_type text not null,
        status text not null default 'pending',
        file_url text,
        file_size bigint,
        created_at timestamp with time zone default now(),
        completed_at timestamp with time zone,
        error_message text,
        metadata jsonb default '{}',
        created_by uuid references profiles(id)
    );
exception
    when duplicate_object then null;
end $$;

-- create indexes
create index if not exists idx_backup_logs_type on backup_logs(backup_type);
create index if not exists idx_backup_logs_status on backup_logs(status);
create index if not exists idx_backup_logs_created_at on backup_logs(created_at);
create index if not exists idx_backup_logs_created_by on backup_logs(created_by);

-- RLS policies
alter table backup_logs enable row level security;

-- Only authenticated users can view logs
create policy "Authenticated users can view backup logs" on backup_logs
    for select
    using (
        auth.role() = 'authenticated'
    );

-- Admins can insert backup logs
create policy "Admins can insert backup logs" on backup_logs
    for insert
    with check (
        exists (
            select 1 from profiles
            where profiles.id = auth.uid()
            and profiles.user_type = 'admin'
        )
    );

-- Only system can update logs
create policy "System can update backup logs" on backup_logs
    for update
    using (
        auth.role() = 'service_role'
    );

-- Only system can delete logs
create policy "System can delete backup logs" on backup_logs
    for delete
    using (
        auth.role() = 'service_role'
    );